stages:
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - self-hosted

test:
  stage: test
  script:
    - npm ci
    - npm test
  tags:
    - self-hosted

deploy:
  stage: deploy
  script:
    - ssh user@server "docker pull $IMAGE_TAG && docker-compose up -d"
  environment:
    name: production
    url: http://your-server-ip
  tags:
    - self-hosted
